export const ROUTES = {
  HOME: '',
  LOGIN: 'login',
  REGISTER: 'register',
  PROFILE: 'profile',
  PRODUCTS: 'products',
  COMPONENTS: 'components',
  SETTINGS: 'settings',
  NOTIFICATIONS: 'notifications'
}

export const FULL_ROUTES = {
  PRIVATE: {
    HOME: `${ROUTES.HOME}/`,
    PROFILE: `${ROUTES.HOME}/${ROUTES.PROFILE}`,
    PRODUCTS: `${ROUTES.HOME}/${ROUTES.PRODUCTS}`,
    COMPONENTS: `${ROUTES.HOME}/${ROUTES.COMPONENTS}`,
    COMPONENT: `${ROUTES.HOME}/${ROUTES.COMPONENTS}/:componentId`,
    SETTINGS: `${ROUTES.HOME}/${ROUTES.SETTINGS}`,
    NOTIFICATIONS: `${ROUTES.HOME}/${ROUTES.NOTIFICATIONS}`
  },
  PUBLIC: {
    LOGIN: `${ROUTES.HOME}/${ROUTES.LOGIN}`,
    REGISTER: `${ROUTES.HOME}/${ROUTES.REGISTER}`
  }
}
